### ISSUE TITLE
Need help on create encryption password for administration 

### ISSUE THREAD

**Issue by tanweiming18042000** [tanweiming18042000/Railway-System-Database-System#1]
Current system doesn't have password encryption for admin, which cause insecurity.

Hope someone to encrypt the password. (Exp: ****)

**Comment by LipSheng9830** [comment]
Hi, can we help to contribute to your project? We want to try out whether we can manage to solve all your issues posted.
bryansheng0251@gmail << email me if possible for a direct message for a detailed discussion.

**Comment by tanweiming18042000** [comment]
Sure, go ahead. 
I will email you the meeting hour as the project might required some setup in order to run it.
