### ISSUE TITLE
Require real-timed based system on every interface

### ISSUE THREAD

**Issue by tanweiming18042000** [tanweiming18042000/Railway-System-Database-System#2]
The current system doesn't show the user or admin current date and time, which would be a nice to add on so that the user would have a sense of current time. 

Wish to add on date and time in the format of DD/MM/YYYY, HH:MM:SS in 1200 format.

**Comment by LipSheng9830** [comment]
Hi, can we help to contribute to your project? We want to try out whether we can manage to solve all your issues posted.
bryansheng0251@gmail << email me if possible for a direct message for a detailed discussion.

**Comment by tanweiming18042000** [comment]
I already reply to you via email, can check it up. 
Nice job for the amendment. I like it very much.
