### ISSUE TITLE
Change the system to only show present and future trips and tickets

### ISSUE THREAD

**Issue by tanweiming18042000** [tanweiming18042000/Railway-System-Database-System#3]
The current version would show the past trips and tickets to user even though the date is past the current date. 

Wish the past trip and ticket would not show to the customer.

**Comment by LipSheng9830** [comment]
Hi, can we help to contribute to your project? We want to try out whether we can manage to solve all your issues posted.
bryansheng0251@gmail << email me if possible for a direct message for a detailed discussion.

**Comment by tanweiming18042000** [comment]
Kindly check your email as I already reply to you through email. 
Thanks for the idea, I like the idea.
