### ISSUE TITLE
Enable to track admin who is in charge of the day

### ISSUE THREAD

**Issue by tanweiming18042000** [tanweiming18042000/Railway-System-Database-System#4]
As for current version, every user is only assigned to the first admin. 
Admin couldn't assigned who will be in charge of today's users. 

Wish to add on: 
i) Admin can assigned which admin will be in charge of the day
ii) Update at the updateMenu().

**Comment by LipSheng9830** [comment]
Hi, can we help to contribute to your project? We want to try out whether we can manage to solve all your issues posted.
bryansheng0251@gmail << email me if possible for a direct message for a detailed discussion.
